robot:
  name: blueboat
  family: surface
  environment: real
  localization: real

description:
  package: blueboat_description
  launch_file: robot_description.launch.py
  xacro: urdf/blueboat.urdf.xacro
  xacro_args:
    environment: real
    robot_namespace: blueboat
    family: surface

ros2_control:
  enabled: true
  launch_package: sura_bringup
  launch_file: sura_controllers.launch.py
  params_package: blueboat_description
  params: config/ros2_control_params.yaml

localization:
  enabled: true
  mode: surface_fastlio
  launch_package: sura_localization
  launch_file: surface_fastlio.launch.py
  publish_tf: true

navigation:
  enabled: true
  mode: surface
  launch_package: sura_navigator
  launch_file: navigator.launch.py

sensors:
  ping_sonar:
    enabled: true
    real_only: true
    package: ping_sonar_ros
    executable: ping1d_node
    port: /dev/ttyAMA3
    speed: 1450000
    interval_num: 100
    gain_num: 1
    scan_start: 100
    scan_lenght: 3000
    mode_auto: 0
    output_topic: /blueboat/sensors/altimeter

teleop:
  enabled: false
  launch_package: sura_teleop
  launch_file: teleop.launch.py
  robot: blueboat

diagnostics:
  enabled: true
  launch_package: sura_diagnostics
  launch_file: diagnostics.launch.py
  params_package: sura_diagnostics
  params: config/blueboat_diagnostics.yaml

imu:
  raw_imu_topic: controller/imu_broadcaster/imu
  filtered_imu_topic: sensors/imu
  mag_topic: magnetometer_broadcaster/mag
